default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db
  pool: 5

development:
  <<: *default
  database: inventario_development

test:
  <<: *default
  database: inventario_test

production:
  <<: *default
  database: inventario_production
